### ISSUE TITLE
onChange interface

### ISSUE THREAD

**Issue by apalmieriGH** [mkyy/mui-search-bar#1]
Shouldn't the _onChange_ API declaration at
https://github.com/mkyy/mui-search-bar/blob/2e7c155abb1ca9223f621b41ba6fb63b31ac53d2/index.d.ts#L19

be fixed by:
`onChange?(query: string): void;` ?

**Comment by mkyy** [comment]
Hello,

Yeah, it should be, thanks for seeing this.
Also, feel free to open a PR fixing this, or wait for a new version with this declaration fix.
